server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    username: root
    password: zaq1234!
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace